version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_secure
    restart: unless-stopped
    ports:
      - "127.0.0.1:8025:8025"  # Web UI - bind to localhost only
      - "127.0.0.1:1025:1025"  # SMTP server - bind to localhost only
    networks:
      - mailhog_network
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"

networks:
  mailhog_network: