version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    shm_size: 128mb
    networks:
      - postgres_network
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-dbuser}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_HOST_AUTH_METHOD: md5  # Secure authentication
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true
    user: "999:999"

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"  # Bind to localhost only
    networks:
      - postgres_network
    depends_on:
      - db
    security_opt:
      - no-new-privileges:true

networks:
  postgres_network: