version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: prestashop_mysql
    networks: 
      - prestashop_network    
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-prestashop}
      MYSQL_USER: ${MYSQL_USER:-prestashopuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    security_opt:
      - no-new-privileges:true
    user: "999:999"

  prestashop:
    container_name: prestashop_app
    image: prestashop/prestashop:1.7
    ports:
      - "127.0.0.1:82:80"  # Bind to localhost only
    env_file:
      - .env
    environment:
      - DB_SERVER=db
      - ADMIN_MAIL=${PRESTASHOP_ADMIN_EMAIL:-admin@localhost.com}
      - ADMIN_PASSWD=${PRESTASHOP_ADMIN_PASSWORD}
      - DB_USER=${MYSQL_USER:-prestashopuser}
      - DB_PASSWD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE:-prestashop}
      - PS_DEMO_MODE=false
      - PS_ERASE_DB=false
      - PS_INSTALL_DB=true
      - PS_DOMAIN=${PRESTASHOP_DOMAIN:-localhost:82}
    volumes:
      - ./presta_data:/var/www/html  
    networks: 
      - prestashop_network
    depends_on:
      - db
    security_opt:
      - no-new-privileges:true

volumes:
  db_data:
  presta_data:
networks: 
  prestashop_network:
