version: '3.8'
services:
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    networks:
      - magento_network
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER:-magento_user}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-magento_db}
    volumes:
      - mariadb_data:/bitnami/mariadb
    security_opt:
      - no-new-privileges:true
    user: "999:999"

  magento:
    image: bitnami/magento:2
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:8080"   # Bind to localhost only
      - "127.0.0.1:443:8443" # Bind to localhost only
    networks:
      - magento_network
    env_file:
      - .env
    environment:
      - MAGENTO_HOST=${MAGENTO_HOST:-localhost}
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=${MARIADB_USER:-magento_user}
      - MAGENTO_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - MAGENTO_DATABASE_NAME=${MARIADB_DATABASE:-magento_db}
    volumes:
      - magento_data:/bitnami/magento
    depends_on:
      - mariadb
    security_opt:
      - no-new-privileges:true

volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local

networks:
  magento_network: